import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import '../../controllers.dart';
import '../../services.dart';
import '../../utilities/constants/colors.dart';
import '../../utilities/constants/textstyles.dart';
import '../../utilities/widgets.dart';
import 'create_pin.dart';
class OtherRegNin extends StatefulWidget {
  const OtherRegNin({Key? key}) : super(key: key);

  @override
  _OtherRegNinState createState() => _OtherRegNinState();
}

class _OtherRegNinState extends State<OtherRegNin> {
  String? pin;
  @override
  Widget build(BuildContext context) {
    return Scaffold(body: SingleChildScrollView(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Container(
            padding: EdgeInsets.only(left: 36.w,right:36.w,top: 77.h),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: <Widget>[
                backButton(context),
                SizedBox(height: 31.h,),
                Text('Identity\nVerification',style: TextStyle(fontSize: 26.sp),),
                SizedBox(height: 10.h,),
                Row(
                  children: [
                    InputBox(hintText: 'Original NIN', controller: origNin, textInputType: TextInputType.text),
                  ],
                ),
                SizedBox(height: 15.h,),
                Container(
                  padding: EdgeInsets.symmetric(horizontal: 10,vertical: 10),
                  decoration: BoxDecoration(
                    color: kWhite,
                    border: Border.all(color: kBlack1),
                    borderRadius: BorderRadius.circular(10)
                  ),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text('The Virtual NIN (vNIN) is designed to replace the raw 11-digit NIN for everyday usage. Where until now, the raw NIN had been shared and stored by various entities mostly without the knowledge (or consent) of the ID Holder or the Custodian of Identity in Nigeria, the NIMC.Virtual NIN consists of 16 alpha-numeric characters that can be generated by dialing this USSD:',
                      style: TextStyle(height: 1.5,fontSize: 18.sp),),
                      SizedBox(height: 5.h,),
                      Text(' *346*3*original NIN*696739#',style: kBoldBlack,),
                    ],
                  ),
                ),

                SizedBox(height: 15.h,),
                Row(
                  children: [
                    InputBox(hintText: 'Virtual NIN', controller: virtNin, textInputType: TextInputType.text),
                  ],
                ),
                SizedBox(height: 15.h,),
                SizedBox(
                  height: 51.h,
                  width: double.infinity,
                  child: ElevatedButton(

                    style: ElevatedButton.styleFrom(
                        backgroundColor: kBlue),
                    onPressed: ()async{

                      spinner(context);
                      final res = await submitReg(context);
                      if(res['statusCode'] == 200){
                        Navigator.pop(context);
                        Navigator.push(
                          context, MaterialPageRoute(builder: (context) =>  CreateTPin()
                      ));
                      }
                      else{
                        Navigator.pop(context);
                        showSnackBar(context, res['errorMessage']);
                      }
                    },
                    child: Text('Next',style: TextStyle(fontSize: 15.sp),),
                  ),
                ),
              ],
            ),
          ),

        ],),
    ));
  }
}
