/// Flutter icons GmapIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GmapIcon
///      fonts:
///       - asset: fonts/GmapIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class GmapIcon {
  GmapIcon._();

  static const _kFontFam = 'GmapIcon';
  static const String? _kFontPkg = null;

  static const IconData ellipse_327_1_1x = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
